development:
  primary:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: storage/development.sqlite3
  cache:
    adapter: sqlite3
    database: storage/cache/development_cache.sqlite3
    migrations_paths: "db/cache/migrate"
